### ISSUE TITLE
ExtraUtils2 pipes don't put cobble in the crucible.

### ISSUE THREAD

**Issue by karlramberg** [Jozufozu/ExNihiloOmnia#1]
The game crashed when I used an ExtraUtils2 transfer pipe for cobble.

http://pastebin.com/dpKHJczg

**Comment by Renadarain** [comment]
Same crash report here - happens also when manually adding cobblestone 

Regards,
Renada

**Comment by Jozufozu** [comment]
Shouldn't crash in the new release, ExtraUtils pipes still don't work, however hoppers and Ender IO conduits do.

**Comment by Renadarain** [comment]
Thank you for the fix :)
