### ISSUE TITLE
Some potential bugs

### ISSUE THREAD

**Issue by SimonMeskens** [Jozufozu/ExNihiloOmnia#101]
I have a private server pack with Omnia and my users are reporting these bugs

- Barrels will fill with water in biomes where it doesn't rain (confirmed for void biome, not sure of others)
- Clay buckets don't seem to work on barrels of water
- I added a config for hammering logs, but it seems like it's buggy, here's the json:

```json
{
      "id": "minecraft:log",
      "meta": 0,
      "behavior": "meta_specific",
      "rewards": [
        {
          "id": "minecraft:planks",
          "meta": 0,
          "amount": 1,
          "baseChance": 100,
          "fortuneModifier": 0
        },
        {
          "id": "betterwithmods:material",
          "meta": 22,
          "amount": 1,
          "baseChance": 100,
          "fortuneModifier": 0
        },
        {
          "id": "betterwithmods:bark",
          "meta": 0,
          "amount": 2,
          "baseChance": 100,
          "fortuneModifier": 0
        }
      ]
    }
```

I get: 3 planks, 1 sawdust and 2 bark. I have this json repeated several times for different tree types, and once in a while, I cut down an oak tree and it gives me jungle planks and bark instead of the oak.

If you need more info on any of these, let me know.

**Comment by SimonMeskens** [comment]
Just confirmed that the clay buckets are indeed clay buckets from the Clay Bucket mod, not sure why they don't work on barrels. Might not be a fault on your end

**Comment by SimonMeskens** [comment]
Another bug: several users reported not being able to break barrels, resulting in different bugs. I gave it a quick try and it seems to be true, breaking the barrel does nothing, it's not removable.

I think I'm going to remove Omnia for a while, until it gets more mature, I've been doing tech support for hours on end after I added it.

**Comment by Jozufozu** [comment]
I have already fixed the bug with barrels, ill take a look at the others

**Comment by SimonMeskens** [comment]
Thanks, I'd really like to use your mod, as it's better at compatibility than Adscensio and the world generation stuff is perfect for my needs.

**Comment by Jozufozu** [comment]
It seems like the issue with hammering logs is that each type has multiple metadata values depending on its orientation. For example, Oak has 0, 4, and 8; Spruce has 1, 5, and 9, etc. Try setting up something like that and tell me if it is still breaking.

**Comment by SimonMeskens** [comment]
Cool, I'll give that a try
