### ISSUE TITLE
[1.2.1] Crash without Forestry

### ISSUE THREAD

**Issue by VaiN474** [Jozufozu/ExNihiloOmnia#103]
Forestry mod is expected?

java.lang.NoClassDefFoundError: forestry/core/items/ItemForestry

[crash log](https://gist.github.com/anonymous/6187a56ca26066c3025b7ac5a3eb93a6)

**Comment by SimonMeskens** [comment]
yup, confirmed

**Comment by homemmakako** [comment]
Yeah, this is a rather anoying crash 😞

**Comment by Jozufozu** [comment]
I'm really sorry about this, but I can't work on Ex Nihilo today, I just don't have the time. Tomorrow, though, I'll have a fix up as soon as possible.

**Comment by NightOps007** [comment]
Seems to only crash on client startup, my server started just fine with 1.2.1
