### ISSUE TITLE
"Ax-ing" barrel doesn't drop item and creates invisible block, must close world and reload, block persists.

### ISSUE THREAD

**Issue by usafphoenix** [Jozufozu/ExNihiloOmnia#109]
In my world on 1.10.2 in sky-exchange modpack i can't break barrels with an ax (well, technically, i can break them but they don't actually disappear or drop an item. instead a glitch occurs where collision turns off or something and if you enter the space the barrel occupied, your character stutters and can't move. closing the world and reopening results in the block re-appearing where it was, having not been broken. 
A.k.a --- barrels persist after breaking with an ax.

**Comment by Jozufozu** [comment]
This was fixed in 7de1a2ae9af19e21dc82477cc007b602ad2aab41
