### ISSUE TITLE
ExtremeReactors Support

### ISSUE THREAD

**Issue by ghost** [Jozufozu/ExNihiloOmnia#111]
In the last commit a3e0e7acc3390943789f99b242f267e2120a9c88 you have insert the bigreactors yellorium support, but in 1.10.2 the mod name is ExtremeReactors-1.10.2-0.4.5.20

**Comment by RealGrep** [comment]
The modID, however, is still bigreactors. For example, note the yellorite ore is bigreactors:brOre:0.

**Comment by ghost** [comment]
Then why i don't see the yellorium/yellorite chunk in the exnihilo object(sieve)

**Comment by RealGrep** [comment]
I'll test it out when I get the chance, @balianor , in case there's an issue. Perhaps there's a mixup in the whole extremereactors/bigreactors stuff, or elsewhere.
EDIT: I do see I missed something, though may or may not have anything to do with this. I didn't add the configs for force_yellorite, as well as the other ones I added after draconium. Ooops.

**Comment by RealGrep** [comment]
Darnit, Jozufozu, I literally just pushed that fix. XD

Anyway, @balianor , I did triple check and the modid is definitely correct. However, I didn't get it to show up until I set force yellorite to true (after fixing the lack of such an option), so not sure the current checks work as expected. But if you let it regenerate your configs, flip that to true, and restart the server, it should all show up.

Well, once you get this fix, anyway.

EDIT: Though for items and everything, the modid is all lower case, as defined in the mcmod.info file, it's camel cased as "BigReactors". It might be that the after:bigreactors line should actually be after:BigReactors. And curse these kinds of inconsistencies. lol

**Comment by ghost** [comment]
For fix the ingot problem just add

 `if (ore == EnumOre.YELLORITE)
                    OreDictionary.registerOre("ingotYellorium", new ItemStack(ENOItems.INGOT_ORE, 1, ore.getMetadata()));`

in ENOOres.java
But i don't find a way to show him the ore of mod without forcing, but for now is an excellent result

I think the Tconstruct fluid compatibility also broken but i've time for now to test this

Edit
Maybe there is a preinit/postinit problem in the ore retrieve
