### ISSUE TITLE
void overworld overwriting all world presets

### ISSUE THREAD

**Issue by SDUBZ** [Jozufozu/ExNihiloOmnia#113]
one example can be shown here http://puu.sh/sHPYc/b5276869b3.png overwriting garden of glass

also the json that overwrited this preset void overworld template"=skyblock_2-1_overworld.json

**Comment by SDUBZ** [comment]
this also overwrites a backed up world also making a another skyblock within the backed up world

the json used from config is: void overworld template"=skyblock_2-1_overworld.json

**Comment by Jozufozu** [comment]
Sorry for not responding sooner. You could replace "skyblock_2-1_overworld.json" with "none" so the line looks like
S:"void overworld template"=none
