### ISSUE TITLE
Issue with broken Recipe spam in FML Log

### ISSUE THREAD

**Issue by DatrixTHLK** [Jozufozu/ExNihiloOmnia#117]
Hello,
I get a bit of spam in the FML Log about certain recipes being broken 
https://github.com/mezz/JustEnoughItems/issues/640
Minecraft: 1.10.2
Forge: 12.18.3.2185
Ex Nihilo Omnia 1.2.1

If you have any questions you can ask mezz

**Comment by Jozufozu** [comment]
I think I know what was causing this and @RealGrep fixed it in d0d4229d984cdf2eb71d12e2af2c348f733d6735

**Comment by DatrixTHLK** [comment]
Thanks for responding and the fix.
