### ISSUE TITLE
iron ingot duplicate & other

### ISSUE THREAD

**Issue by ghost** [Jozufozu/ExNihiloOmnia#118]
In the last build/commit
[Immage 1](http://i64.tinypic.com/inbv5d.png)
[Immage 2](http://i64.tinypic.com/hunmdh.png)

**Comment by Jozufozu** [comment]
The item.null.names are there so when somebody updates from a previous version, their ores won't just disappear. I changes the back-end of the ore system completely yesterday, and as result the ids of all the blocks had to change.
The ingot ore dict thing is an oversight on my part.
