### ISSUE TITLE
(CRASH) java.lang.NoClassDefFoundError: forestry/core/items/ItemForestry

### ISSUE THREAD

**Issue by Vaygrim** [Jozufozu/ExNihiloOmnia#121]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingHook (Mekanism-1.10.2-9.2.0.294.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.2.9.jar)
  ForgelinPlugin (Forgelin-1.1.0.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.6.jar)
  LoadingPlugin (Quark-r1.1-66.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.61-beta.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 12/14/16 2:39 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ex Nihilo Omnia (exnihiloomnia)
Caused by: java.lang.NoClassDefFoundError: forestry/core/items/ItemForestry
	at exnihiloomnia.proxy.ClientProxy.preInit(ClientProxy.java:52)
	at exnihiloomnia.ENO.preInitialize(ENO.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: forestry.core.items.ItemForestry
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 499040928 bytes (475 MB) / 2061500416 bytes (1966 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 99 mods loaded, 99 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCH	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCH	actuallyadditions{1.10.2-r90} [Actually Additions] (ActuallyAdditions-1.10.2-r90.jar) 
	UCH	Baubles{1.3.8} [Baubles] (Baubles-1.10.2-1.3.8.jar) 
	UCH	Botania{r1.9-339} [Botania] (Botania r1.9-339.jar) 
	UCH	AkashicTome{1.0-5} [Akashic Tome] (AkashicTome-1.0-5.jar) 
	UCH	JEI{3.13.6.387} [Just Enough Items] (jei_1.10.2-3.13.6.387.jar) 
	UCH	appleskin{1.0.4} [AppleSkin] (AppleSkin-mc1.10.2-1.0.4.jar) 
	UCH	Psi{r1.0-42} [Psi] (Psi-r1.0-42.jar) 
	UCH	Quark{r1.1-66} [Quark] (Quark-r1.1-66.jar) 
	UCH	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCH	baconators{3.0.3} [Baconators] (baconators-1.10.2-3.0.3.jar) 
	UCH	bdlib{1.12.2.17} [BD Lib] (bdlib-1.12.2.17-mc1.10.2.jar) 
	UCH	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCH	BloodMagic{1.9.4-2.1.0-69} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-69.jar) 
	UCH	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCH	chisel{MC1.10.2-0.0.7.7} [Chisel] (Chisel-MC1.10.2-0.0.7.7.jar) 
	UCH	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCH	chiselsandbits{12.8} [Chisels & Bits] (chiselsandbits-12.8.jar) 
	UCH	combathelp{1.0.4} [Combat Help] (combathelp-1.10-1.0.4.jar) 
	UCH	cyclopscore{0.8.2} [Cyclops Core] (CyclopsCore-1.9.4-0.8.2.jar) 
	UCH	commoncapabilities{1.2.1} [CommonCapabilities] (CommonCapabilities-1.9.4-1.2.1.jar) 
	UCH	cookingforblockheads{4.2.26} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.26.jar) 
	UCH	craftingtweaks{6.1.16} [Crafting Tweaks] (CraftingTweaks_1.10.2-6.1.16.jar) 
	UCH	MineTweaker3{3.0.14} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.15.jar) 
	UCH	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.15.jar) 
	UCH	CustomMainMenu{2.0.2} [Custom Main Menu] (CustomMainMenu-MC1.10.2-2.0.2.jar) 
	UCH	cyberware{beta-0.2.5} [Cyberware] (cyberware-1.9.4-1.10.2-beta-0.2.5.jar) 
	UCH	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.3.6.1_1.10.2.jar) 
	UCH	props{2.3.6.1} [Decocraft] (Decocraft-2.3.6.1_1.10.2.jar) 
	UCH	disenchanter{1.4} [Disenchanter] (disenchanter-[1.9.4]1.4.jar) 
	UCH	StorageDrawers{1.10.2-3.5.12} [Storage Drawers] (StorageDrawers-1.10.2-3.5.12.jar) 
	UCH	bitdrawers{0.35} [Drawers & Bits] (DrawersBits-1.10.2-0.35.jar) 
	UCH	lootablebodies{2.2.0} [DrCyano's Lootable Bodies] (DrCyanosLootableBodies_1.10.2-2.2.0.jar) 
	UCH	endercore{1.10.2-0.4.1.61-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.61-beta.jar) 
	UCH	EnderIO{1.10.2-3.0.1.141_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.141_beta.jar) 
	UCH	shetiphiancore{3.3.6} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.6.jar) 
	UCH	endertanks{1.4.9} [EnderTanks] (endertanks-1.10.0-1.4.9.jar) 
	UCH	mantle{1.10.2-1.1.3.199} [Mantle] (Mantle-1.10.2-1.1.3.jar) 
	UCH	tconstruct{1.10.2-2.6.1.464} [Tinkers' Construct] (TConstruct-1.10.2-2.6.1.jar) 
	UCE	exnihiloomnia{1.2.1} [Ex Nihilo Omnia] (exnihiloomnia-1.2.1.jar) 
	UCH	excompressum{2.0.56} [Ex Compressum] (ExCompressum_1.10.2-2.0.56.jar) 
	UCH	expandablebackpack{1.1} [Expandable Backpacks] (expandableBackpacks1.1.10-1.10.2.jar) 
	UCH	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.1.3a.jar) 
	UCH	FastLeaveDecay{1.2.3} [Fast Leave Decay] (FastLeaveDecay-MC1.10.2-1.2.3.jar) 
	UCH	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	UCH	FloodLights{1.2.7-145} [Flood Lights] (FloodLights-1.9.4-1.2.7-145.jar) 
	UCH	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.1.5.jar) 
	UCH	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.1.4.jar) 
	UCH	gearswap{1.4.0} [Gear Swapper] (gearswap-1.1x-1.4.0.jar) 
	UCH	pressure{1.3.1.18} [Pressure Pipes] (pressure-1.3.1.18-mc1.10.2.jar) 
	UCH	advgenerators{0.9.20.18} [Advanced Generators] (generators-0.9.20.18-mc1.10.2.jar) 
	UCH	giacomosfoundry{1.3.6} [Giacomo's Foundry] (GiacomosFoundry1.10.2-1.3.6.jar) 
	UCH	helpfixer{1.0} [HelpFixer] (HelpFixer-1.10.2-1.4.15.jar) 
	UCH	integrateddynamics{0.6.4} [Integrated Dynamics] (IntegratedDynamics-1.10.2-0.6.4.jar) 
	UCH	inventorysorter{0.10.0+42} [Simple Inventory sorting] (inventorysorter-1.10-0.10.0+42.jar) 
	UCH	journeymap{1.10.2-5.3.2} [JourneyMap] (journeymap-1.10.2-5.3.2.jar) 
	UCH	jeresources{0.5.7.87} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.7.87.jar) 
	UCH	malisiscore{1.10.2-4.2.9} [MalisisCore] (malisiscore-1.10.2-4.2.9.jar) 
	UCH	malisisblocks{1.10.2-4.1.3} [Malisis Blocks] (malisisblocks-1.10.2-4.1.3.jar) 
	UCH	malisisdoors{1.10.2-5.1.6} [MalisisDoors] (malisisdoors-1.10.2-5.1.6.jar) 
	UCH	Mekanism{9.2.0} [Mekanism] (Mekanism-1.10.2-9.2.0.294.jar) 
	UCH	MekanismGenerators{9.2.0} [MekanismGenerators] (MekanismGenerators-1.10.2-9.2.0.294.jar) 
	UCH	MekanismTools{9.2.0} [MekanismTools] (MekanismTools-1.10.2-9.2.0.294.jar) 
	UCH	ModNameTooltip{1.6.0} [Mod Name Tooltip] (modnametooltip_1.10.2-1.6.0.jar) 
	UCH	Morpheus{1.10.2-3.1.12} [Morpheus] (Morpheus-1.10.2-3.1.12.jar) 
	UCH	multistorage{1.2.11} [Multi-Storage] (multistorage-1.10.0-1.2.11.jar) 
	UCH	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
	UCH	notenoughwands{1.5.2} [Not Enough Wands] (notenoughwands-1.1x-1.5.2.jar) 
	UCH	nullplayerexception{1.0} [Null Player Exception] (nullplayerexception-1.10.2-1.0.1.jar) 
	UCH	oretweaker{1.0.2-1.10.2} [Ore Tweaker] (OreTweaker-1.0.2-1.10.2.jar) 
	UCH	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCH	ping{1.2.2} [Ping] (Ping-1.10.X-1.2.2.B7-universal.jar) 
	UCH	platforms{1.2.7} [Platforms] (platforms-1.10.0-1.2.7.jar) 
	UCH	pocketnether{2.3} [Pocket Nether Link] (PocketNetherLink-1.10.2-2.3.jar) 
	UCH	possessed{1.0.0} [Possessed] (possessed-1.0.0.jar) 
	UCH	psionup{15.1} [PSIonic Upgrades] (PSIonicUpgrades-r1.15.jar) 
	UCH	quantumflux{2.0.9} [QuantumFlux] (quantumflux-1.10.2-2.0.9.jar) 
	UCH	randomthings{3.7.7} [Random Things] (RandomThings-MC1.10.2-3.7.7.jar) 
	UCH	rangedpumps{0.3} [Ranged Pumps] (rangedpumps-0.3.jar) 
	UCH	refinedstorage{1.2.11} [Refined Storage] (refinedstorage-1.2.11.jar) 
	UCH	xreliquary{1.10.2-1.3.3.585} [Reliquary] (Reliquary-1.10.2-1.3.3.585.jar) 
	UCH	rflux{0.1.0} [RF Lux] (rflux-0.1.0.jar) 
	UCH	rftools{5.71} [RFTools] (rftools-1.1x-5.71.jar) 
	UCH	rftoolscontrol{1.6.3} [RFTools Control] (rftoolsctrl-1.1x-1.6.3.jar) 
	UCH	rftoolsdim{4.51} [RFTools Dimensions] (rftoolsdim-1.1x-4.51.jar) 
	UCH	roots{0.208} [Roots] (roots-0.208.jar) 
	UCH	shadowmc{3.5.0} [ShadowMC] (ShadowMC-1.10.2-3.6.0.jar) 
	UCH	shearmadness{1.10.2} [Shear Madness] (shearmadness-1.10.2-1.4.0.jar) 
	UCH	SleepingBag{1.4.0} [Sleeping Bag] (SleepingBag-1.10.2-1.4.0.jar) 
	UCH	supercraftingframe{1.2.1.88} [Super Crafting Frame] (supercraftingframe-1.10.2-1.2.1.88.jar) 
	UCH	theoneprobe{1.3.3} [The One Probe] (theoneprobe-1.10-1.3.3.jar) 
	UCH	topaddons{1.10.2-0.9.0} [TOP Addons] (topaddons-1.10.2-0.9.0.jar) 
	UCH	trashslot{6.3.7} [TrashSlot] (TrashSlot_1.10.2-6.3.7.jar) 
	UCH	treegrowingsimulator{0.0.4} [Tree Growing Simulator 2016] (TreeGrowingSimulator2016-0.0.4.jar) 
	UCH	waterstrainer{1.3.2} [Water Strainer] (WaterStrainer-1.9.4-1.3.2.jar) 
	UCH	wired{1.3.3} [WIRED: More Augs] (WIRED-1.3.3.jar) 
	UCH	Woot{1.10.2-1.2.3} [Woot] (woot-1.10.2-1.2.3.jar) 
	Loaded coremods (and transformers): 
LoadingHook (Mekanism-1.10.2-9.2.0.294.jar)
  
MalisisCorePlugin (malisiscore-1.10.2-4.2.9.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
ForgelinPlugin (Forgelin-1.1.0.jar)
  
LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  lumien.randomthings.asm.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.6.jar)
  shetiphian.core.asm.ClassTransformer
LoadingPlugin (Quark-r1.1-66.jar)
  vazkii.quark.base.asm.ClassTransformer
ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  team.chisel.common.asm.ChiselTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.61-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 375.70' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* actuallyadditionsapi (29) from ActuallyAdditions-1.10.2-r90.jar
		* Baubles|API (1.3.1.2) from Baubles-1.10.2-1.3.8.jar
		* BloodMagic|API (@VERSION@) from BloodMagic-1.9.4-2.1.0-69.jar
		* BotaniaAPI (85) from Botania r1.9-339.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.10.2-0.0.7.7.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.10.2-0.0.7.7.jar
		* ChiselsAndBitsAPI (12.5.0) from chiselsandbits-12.8.jar
		* CoFHAPI (1.8.9R1.2.0B1) from rangedpumps-0.3.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from ActuallyAdditions-1.10.2-r90.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.1.jar
		* commoncapabilities|api (0.0.1) from CommonCapabilities-1.9.4-1.2.1.jar
		* compatlayer (0.1.4) from compatlayer-1.10-0.1.4.jar
		* CraftingTweaks|API (4.1) from CraftingTweaks_1.10.2-6.1.16.jar
		* CSLib|API (0.3.0) from Decocraft-2.3.6.1_1.10.2.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.10.2-3.0.1.141_beta.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.10.2-3.0.1.141_beta.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.10.2-3.0.1.141_beta.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.10.2-3.0.1.141_beta.jar
		* Guide-API|API (1.10.2-2.0.2-45) from Guide-API-1.10.2-2.0.2-45.jar
		* integrateddynamics|api (0.2.0) from IntegratedDynamics-1.10.2-0.6.4.jar
		* jeresources|API (0.5.7.87) from JustEnoughResources-1.10.2-0.5.7.87.jar
		* journeymap|client-api (1.3) from journeymap-1.10.2-5.3.2.jar
		* journeymap|client-api-display (1.3) from journeymap-1.10.2-5.3.2.jar
		* journeymap|client-api-event (1.3) from journeymap-1.10.2-5.3.2.jar
		* journeymap|client-api-model (1.3) from journeymap-1.10.2-5.3.2.jar
		* journeymap|client-api-util (1.3) from journeymap-1.10.2-5.3.2.jar
		* JustEnoughItemsAPI (4.10.1) from jei_1.10.2-3.13.6.387.jar
		* mcjtylib_ng (2.3.1) from mcjtylib-1.1x-2.3.1.jar
		* MekanismAPI|core (9.0.0) from Mekanism-1.10.2-9.2.0.294.jar
		* MekanismAPI|energy (9.0.0) from Mekanism-1.10.2-9.2.0.294.jar
		* MekanismAPI|gas (9.0.0) from Mekanism-1.10.2-9.2.0.294.jar
		* MekanismAPI|infuse (9.0.0) from Mekanism-1.10.2-9.2.0.294.jar
		* MekanismAPI|laser (9.0.0) from Mekanism-1.10.2-9.2.0.294.jar
		* MekanismAPI|reactor (9.0.0) from Mekanism-1.10.2-9.2.0.294.jar
		* MekanismAPI|recipe (9.0.0) from Mekanism-1.10.2-9.2.0.294.jar
		* MekanismAPI|transmitter (9.0.0) from Mekanism-1.10.2-9.2.0.294.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.10.2-9.2.0.294.jar
		* pressureAPI (1.3.1.18) from pressure-1.3.1.18-mc1.10.2.jar
		* PsiAPI (2) from Psi-r1.0-42.jar
		* PSIonicUpgradesAPI (1) from PSIonicUpgrades-r1.15.jar
		* shearmadness.api (@API_VERSION@) from shearmadness-1.10.2-1.4.0.jar
		* shearmadness_api_plumbing (1.0) from shearmadness-1.10.2-1.4.0.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.5.12.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from refinedstorage-1.2.11.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.5.12.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.5.12.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.5.12.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from refinedstorage-1.2.11.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from refinedstorage-1.2.11.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from refinedstorage-1.2.11.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.5.12.jar
	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/E:/GAMES/CurseVoice/Instances/Vaygrim's%20Chance%204%20(1)/mods/Mekanism-1.10.2-9.2.0.294.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/E:/GAMES/CurseVoice/Instances/Vaygrim's%20Chance%204%20(1)/mods/Mekanism-1.10.2-9.2.0.294.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/E:/GAMES/CurseVoice/Instances/Vaygrim's%20Chance%204%20(1)/mods/Mekanism-1.10.2-9.2.0.294.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/E:/GAMES/CurseVoice/Instances/Vaygrim's%20Chance%204%20(1)/mods/Mekanism-1.10.2-9.2.0.294.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/E:/GAMES/CurseVoice/Instances/Vaygrim's%20Chance%204%20(1)/mods/Mekanism-1.10.2-9.2.0.294.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/E:/GAMES/CurseVoice/Instances/Vaygrim's%20Chance%204%20(1)/mods/Mekanism-1.10.2-9.2.0.294.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/E:/GAMES/CurseVoice/Instances/Vaygrim's%20Chance%204%20(1)/mods/Mekanism-1.10.2-9.2.0.294.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/E:/GAMES/CurseVoice/Instances/Vaygrim's%20Chance%204%20(1)/mods/Mekanism-1.10.2-9.2.0.294.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/E:/GAMES/CurseVoice/Instances/Vaygrim's%20Chance%204%20(1)/mods/Mekanism-1.10.2-9.2.0.294.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

**Comment by Vaygrim** [comment]
NOTE: Turning OFF the compatibility settings for Forestry does NOT get around this issue. That stuff still gets loaded.

**Comment by Jozufozu** [comment]
I'm aware of this crash, and it has been fixed already. I've been waiting on pushing an update because the mod is still broken in places and I haven't had much time to work. I will leave this open so no more duplicate issues get submitted.

**Comment by Vaygrim** [comment]
If I understand you right.. you won't push out one fix because there are other things that you want to fix also? We can't get a minor version update that just resolves this crash? Cause right now v1.2.1 is completely useless, and 1.2.0 is a bit of a mess.

**Comment by Jozufozu** [comment]
You are absolutely right, I should have done that, but I got carried away implementing a new ore system. If there is a "next time" for a bug as big as the forestry crash I will be sure to do that right away.
