### ISSUE TITLE
End Cake Doesn't Work in MP

### ISSUE THREAD

**Issue by MasterGeneral156** [Jozufozu/ExNihiloOmnia#123]
Using version 1.2.1, the end cake doesn't appear to work in multiplayer. Tested working in single player. Clicking on the cake to use it, doesn't teleport the player. It also doesn't eat a slice.

**Comment by Jozufozu** [comment]
Are you sure your player is hungry? They need to be to use it, but that can be disabled in the mod's config.

**Comment by MasterGeneral156** [comment]
I'm laughing my arse off. Yes. That's the issue. xD Thanks and my apologies!
