### ISSUE TITLE
add a check to yellorite

### ISSUE THREAD

**Issue by ghost** [Jozufozu/ExNihiloOmnia#125]
add a check if yellorite ingot is registered to uranium or not

**Comment by Jozufozu** [comment]
May I ask why? I don't really see the reason to.

**Comment by ghost** [comment]
because I want to separate the two resources, I do not obtain the yellorite from uranium and vice versa, which allows me to make the big reactor in config, but it is a minor problem


Edit:
the best way would get them back a big reactor ingot instead of creating another

**Comment by ghost** [comment]
It's the same, but you can remove this piece
`.addOreDictName("ingotYellorium").addOreDictName("ingotUranium")` 
only for clear the code or It's still used

**Comment by Jozufozu** [comment]
I'll leave it just in case
