### ISSUE TITLE
Osmium Problem

### ISSUE THREAD

**Issue by ghost** [Jozufozu/ExNihiloOmnia#127]
Only the osmium needs to be put into whitelist to be seen, the other metals are working properly

**Comment by ghost** [comment]
the fix for the osmium seems not to work;

change:

`register(new Ore("osmium", new Color("608FC4"), 20, true, false, false));`
to
`register(new Ore("osmium", new Color("608FC4"), 20, true, false, false).setParentMod("Mekanism"));`

**Comment by Jozufozu** [comment]
Duh, thank you
