### ISSUE TITLE
melting speed too slow!!

### ISSUE THREAD

**Issue by NarigudoBR** [Jozufozu/ExNihiloOmnia#129]
in the 1.7.10 and 1.6.4 versions of Ex Nihilo the melting speed was 0,1 mb/t under a torch, while this version is 1mb/s!!!! is half of the older speed( 0,1mb X 20 ticks is 2 mb/s !!!) yeah it took 16,67 min when it should be taken about 8,4 minutes!!

**Comment by Jozufozu** [comment]
Torch melting speed increased in 7b61aa8afc55e7a835249d8c4fbd5c1031f1b369
