### ISSUE TITLE
Client Crash When Using Mechanical User From Extra Utilities 2 on Sieve

### ISSUE THREAD

**Issue by MasterGeneral156** [Jozufozu/ExNihiloOmnia#13]
Right, so I love automation, and to quench my thirst while I wait for Ex Nihilo automation mods to come forward and update, I thought I could use the Mechanical User temporarily.

http://pastebin.com/D9de9zGX

Note, this only crashed me.

**Comment by Jozufozu** [comment]
I don't think the mechanical user is from Ender IO, but the one from ExtraUtils2 isn't causing a crash for me. Are you sure you are using the most recent version of the mod?

**Comment by MasterGeneral156** [comment]
My apologies. As I was writing this thread, I believe I was talking Ender IO to a friend.

I haven't tested with the latest version, I believe that I'm currently on 1.0.0 still. I'll test in the morning and let you know!

**Comment by MasterGeneral156** [comment]
You'd be correct that its working in the latest version (1.0.3)

Found a new bug, though. I'll make its issue for it, however.

[/closed]
