### ISSUE TITLE
[1.10.2] Duplication Glitch

### ISSUE THREAD

**Issue by YOYOK9** [Jozufozu/ExNihiloOmnia#134]
Found a duplication glitch when using a hammer (any type).  After testing I can confirm that it seems to do this with each type of Double compressed block from Extrautils 2, Ex: When I break a double compressed block with a normal hammer instead of getting just 1 block of compressed block or 9 of the lower tier.  
pic of amount given: http://puu.sh/t57DT/180ab44392.png

**Comment by YOYOK9** [comment]
Just did another test. If u try to break a higher compressed block it will also duplicate, however it will take longer to break.

**Comment by Jozufozu** [comment]
Like @blay09 said, most likely issue with spongeforge or configs
