### ISSUE TITLE
Add ability to disable default rewards

### ISSUE THREAD

**Issue by WesTroy** [Jozufozu/ExNihiloOmnia#138]
Apologies if this exists in the registries already. 

I spent all morning trying to disable glowstone from the sieve rewards, and cannot figure out how to override defaults. I enabled the default.json files, etc., and played around with those, as well as creating new jsons. You can ADD rewards, but I can't see how to REMOVE rewards.

Am I missing something? Or is the feature not quite in place yet? Thanks!

**Comment by Jozufozu** [comment]
You can not remove individual rewards, but you can disable all default rewards for each registry. You can then copy the registry dump file and remove any recipes you don't want.

**Comment by Jozufozu** [comment]
The registry dump files have to be enabled through the config

**Comment by WesTroy** [comment]
Thanks for the reply - it's a low-priority issue, so whenever you have a free moment, please explain fully how to "disable all default rewards" for a particular registry. I must be missing a step somewhere.

In testing, I used just ExNihiloOmnia 1.2.5 and JEI 1.10.2-3.14.3.403.
The only config change was "transfer all registries to json files"=true.

I copy a defaults.json file to test.json. No changes are made to defaults.json (those files reset their values upon game launch, which is the expected behavior).

If I change any/all values in test.json, however, BOTH files load their registry entries in-game. This means you see double entries of materials - one with defaults.json values, and one with test.json's modified values.

I'm doing something wrong... at your convenience, any specific help is greatly appreciated. Thank you again!

**Comment by Jozufozu** [comment]
You want to change "load default ... recipes" to false for everything you want to change. Then it won't double load the registries.

**Comment by WesTroy** [comment]
That's perfect - and so damn obvious in hindsight. Awesome answer - thanks. Closed!
