### ISSUE TITLE
crucible does not allow fluid to be piped from the sides

### ISSUE THREAD

**Issue by Xalorous** [Jozufozu/ExNihiloOmnia#139]
Crucible does not allow fluid to be piped out of it from the sides.
Tried with EnderIO fluid conduit, pressurized fluid conduit, and fluid transfer node from ExU2.

Fluid can be piped out from the top only.

If this is desired/intended behavior, it should be documented.

**Comment by Jozufozu** [comment]
I'm really sorry for the lack of documentation for this mod. There is a config option to allow for pipe interaction from all sides of the crucible. It's under "automation"
