### ISSUE TITLE
Config option request

### ISSUE THREAD

**Issue by MrAmericanMike** [Jozufozu/ExNihiloOmnia#140]
Would it be possible to have a config to change the durability of the meshes? I really like the concept of meshes that were out, but I would like to be able to change the durability on those.

Thanks a lot.

**Comment by Jozufozu** [comment]
I don't see a reason not to. I'll have this in the next update!

**Comment by MrAmericanMike** [comment]
Thanks a lot. Really enjoying the mod so far. Just missing a way to automate the sieve. Not laziness, but I love to make "farms" of sieves spiting the items out and pushing them with fans into vaccum suckers or conveyor belts. :P

**Comment by Jozufozu** [comment]
I should really document the mod a bit more. You can enable sieve/pipe/hopper interaction in the config.

**Comment by MrAmericanMike** [comment]
Yes that I did and thanks god it's there :D but I believe the old Ex-Nihilo had also an option to enable machines, like the old Autonomous Activator to work on the sieves or not.
I tried without success using the Extra Utilities 2 Mechanical User. Maybe some other machine can do it.
Thanks on the feedback ;)

**Comment by Jozufozu** [comment]
I just tested it in my dev world, you need to set the user to "Activate Block with Item"

**Comment by MrAmericanMike** [comment]
:O Great news, I will set that in my world, I love that kind of setup :D

Thanks a lot for taking the time on testing it ;) <3 <3 <3
