### ISSUE TITLE
Problems with custom recipes through whitelist.txt

### ISSUE THREAD

**Issue by BobyTheDragon** [Jozufozu/ExNihiloOmnia#143]
Hi, I seem to be having some trouble with trying to add custom items and ores to your mod via the whitelist.txt file located in your config folder.

I have 2 problems.

**1.** I have my own mod that's still a WIP. And for a skyblocks server that a friend and I are trying to create. When I try to add in Boron (My mods material) it works fine but the naming of the blocks (Sand, Gravel, Dust) just seem to be "%s Ore Sand" and such. I don't know If I screwed something up somewhere but the item names are just fine for broken, crushed and dust. Here is the code in the whitelist file:
`{
  "entries": [
    {
      "name": "boron",
      "color": "7E7E7E",
      "rarity": 10,
      "hasGravel": true,
      "hasNether": false,
      "hasEnd": false,    
      "ingot": "bobyex:ItemBoronIngot",
      "oreDictNames": [
        "ingotBoron"
      ]
    }
  ]
}`
Just to be clear `bobyex:ItemBoronIngot` is my mods ingot

**2.** How would I add an item to a sieve without making it an ore? For example, Blaze powder, Lapis and such? I have a another material in my mod called Enderpulvis which already is a type of dust.

**Comment by Jozufozu** [comment]
1 is happening because when ex nihilo realizes that tile.ore_sand.boron.name does not exist in the lang file it tries to create a generic name using the %s thing. Weird that that doesn't work. I'll look into it. 
For 2, you can add items to the sieve with the sieve registry jsons. An example is located in /registries/sieve

**Comment by BobyTheDragon** [comment]
Thanks, Also I looked at the sieve folder and your examples there but I cant see a whitelist.txt file. Do I just make one or do I add the code from the sieve into the ores whitelist file?

**Comment by Jozufozu** [comment]
The whitelist.txt is only for ores and is in case ex nihilo doesn't recognize that one of the default ores exist. You only need to touch it if, say, aluminum doesn't show up in your pack when you know it should.

**Comment by BobyTheDragon** [comment]
Ok, So I looked at the example code for the sieve and I think I got it right, How do I get exnihlo to load it in if I don't do it through the whitelist for ores?

AKA where to I put the code basically?

**Comment by BobyTheDragon** [comment]
Nevermind figured out the sieve problem... I forgot and "i" in exnihiloomnia:gravel_ender
