### ISSUE TITLE
all of Actually Additions seeds can not get

### ISSUE THREAD

**Issue by subtank** [Jozufozu/ExNihiloOmnia#147]
i'd love the Actually Additions mod but i can loot the seed,can you give me an example to add the seed into dirt loot.
translation by google,so sorry about my pool english.

**Comment by HenryRichard** [comment]
This isn't really a bug.

If you look in the config/ExNihiloOmnia/registries folder, you can see a ton of different things that you can customize. I assume that by add it to dirt loot (stupid google translate) you mean add to sieving dirt. You would do that with a .json file in the sieve folder with something like this:
https://hastebin.com/oputoyorit.json
I'll let you add the rest yourself.

**Comment by subtank** [comment]
ok i will try it
