### ISSUE TITLE
Any Possibility of an update to 1.11 or 1.12?

### ISSUE THREAD

**Issue by Tylerun** [Jozufozu/ExNihiloOmnia#155]
Hey just curious if theirs any possibility of getting an update?

**Comment by Jozufozu** [comment]
Yes. But it might take a while. I'm not happy with much of the code or even really the mod as it is, and have decided to re-write it for 1.12. Do not expect any results soon, but know that I'm finally picking up this project again.

**Comment by Tylerun** [comment]
Aight thanks for the heads up. Tired of skyfactory and looking to make our own pack in 1.12 and wanted to be the first. Good luck on the rewrite!
