### ISSUE TITLE
Another Mechanical User Issue

### ISSUE THREAD

**Issue by MasterGeneral156** [Jozufozu/ExNihiloOmnia#18]
Right, recently fixed up #13. Upon further testing, I've found that if you attempt to place another mesh on top of another one, it causes a server crash.
As of this moment, I've only tested it with 1.0.3, and a mechanical user.

Crash report:
http://pastebin.com/bhLNyHnT

Looking over the crash report, it seems more like Extra Utilities is as fault. I'll also forward that dev the crash report as well.

**Comment by Jozufozu** [comment]
Maybe I changed something that fixes this without knowing, but this doesn't happen for me. I'll leave this alone for now but I think it is fixed.
