### ISSUE TITLE
Error in TileEntityCrucible from latest merge

### ISSUE THREAD

**Issue by VaiN474** [Jozufozu/ExNihiloOmnia#22]
Something happened with the [TileEntityCrucible.java](https://github.com/Jozufozu/ExNihiloOmnia/blob/2f2a3e50ffbd0de995d6134ae44dad0a656320c2/src/main/java/exnihiloomnia/blocks/crucibles/tileentity/TileEntityCrucible.java#L14) file in the latest merge.

**Comment by SoftPoison** [comment]
A quick ctrl+f of [my pr](https://github.com/Jozufozu/ExNihiloOmnia/pull/21/files) indicates that the problem may have arisen from merging the pr. @Jozufozu did you use the GitHub for Windows client for the merge (if that is even possible)?

**Comment by SoftPoison** [comment]
[Here's the diff](https://github.com/Jozufozu/ExNihiloOmnia/commit/2f2a3e50ffbd0de995d6134ae44dad0a656320c2#diff-381f78a4b68ba55ec0380e39cf3022a3R70) btw and one of the affected files (just search for `<<<<<<< HEAD` to find the rest)

**Comment by Jozufozu** [comment]
Yeah, completely missed that somehow. Fixed.
