### ISSUE TITLE
Crash when putting water in a barrel with a bucket.

### ISSUE THREAD

**Issue by mjuksel** [Jozufozu/ExNihiloOmnia#26]
I've tested the issue in a fresh instance without mods, and this does not appear to happen there.

However, with a few mods installed i get this error http://pastebin.com/ktcYvDQC
Edit: I see you just edited the barrels 12 minutes ago. 
Edit2: Noticed i had v1.0.1 , tried v1.0.2 and it works there. Sorry 👍

**Comment by Jozufozu** [comment]
Any reason you reopened this? If not, then look out for 1.0.3 which fixes every bug known to man.

**Comment by mjuksel** [comment]
Nah i was checking if i can delete my own post. Not really used github a lot.
 Closing it now 👍
