### ISSUE TITLE
Unable to add fluids to barrels

### ISSUE THREAD

**Issue by jwmwebdev** [Jozufozu/ExNihiloOmnia#27]
I am unable to add any fluid (tested water, lava, milk) to a barrel (tested oak and stone) using buckets or fluid conduits. You have the water-splash sound, but no change in the barrel.

version 1.0.3, forge 2073. 

Maybe a separate bug but the conduits from EnderIO are not connecting to the sides of the crucible, but they are connecting to the top. The EnderIO version I am running is 1.10.2-3.0.1.107-beta

**Comment by Jozufozu** [comment]
Pipes are only allowed to connect to the crucible from the top. I'll look into the other thing
