### ISSUE TITLE
Osmium can't be enabled

### ISSUE THREAD

**Issue by VaiN474** [Jozufozu/ExNihiloOmnia#34]
Osmium ore is not detected from the ore dictionary and the forced option in config does not add it. It seems there's a check missing [here](https://github.com/Jozufozu/ExNihiloOmnia/blob/d5cafb84c166033d819c2b7538f43558ec5b54e8/src/main/java/exnihiloomnia/compatibility/ENOOres.java#L79).

**Comment by Jozufozu** [comment]
Thank you!
