### ISSUE TITLE
Witchwater from mycellium blocks

### ISSUE THREAD

**Issue by Drakma** [Jozufozu/ExNihiloOmnia#37]
Does ENO not support making witchwater?  I placed water in barrels with mycellium around it, but it does not make witchwater.

**Comment by SoftPoison** [comment]
[Right click a barrel of water with spores](https://github.com/Jozufozu/ExNihiloOmnia/blob/master/src/main/java/exnihiloomnia/blocks/barrels/states/fluid/logic/FluidTransformWitchwater.java#L25)

**Comment by Jozufozu** [comment]
I might add the old way back in, this was an "artifact" of the Ex Nihilo 2 port

**Comment by Drakma** [comment]
That might be a good way to go for automation's sake.

On Sep 21, 2016, at 11:51 PM, Jozufozu <notifications@github.com<mailto:notifications@github.com>> wrote:

I might add the old way back in, this was an "artifact" of the Ex Nihilo 2 port

**Comment by Jozufozu** [comment]
You can still automate it if you pump in water and spores, barrels do support pipes

**Comment by BlayTheNinth** [comment]
I think the current way is fine, but it should be documented in JEI. Ex Compressum used to add [NEI support for barrels](https://github.com/blay09/ExCompressum/blob/master/src/main/resources/assets/excompressum/textures/gui/neiBarrelProcess.png), but since this mod is now actively developed it probably fits better to be implemented here.

**Comment by MatthiasMann** [comment]
If we need one spore per soul sand block - and soul sand blocks are needed for quartz - then the drop chance for the spores should be increased.

Alternative a way to duplicate/multiply the witch water would be nice. Maybe surround a barrel filled with Witchwater with a barrel filled with water - then the Witchwater barrel will empty and the surrounding barrels will transform to Witchwater? Could be fun to automate that :)

Personally I prefer the mycelium surrounded barrel to make witch water - having more multi block constructs in the game is fine.

**Comment by MatthiasMann** [comment]
It seems a (oak) barrel which was used to make soul sand remembers that it had Witchwater in it - filling it again with a bucket of water results in a barrel filled with Witchwater - while this is an easy way to multiply Witchwater I think it is a bug?

**Comment by MatthiasMann** [comment]
This bug also prevents a barrel from being filled via pipes - breaking and placing the barrel again allows it to be filled correctly. So this makes it currently impossible to automate soul sand.
