### ISSUE TITLE
Mod Conflict

### ISSUE THREAD

**Issue by Ravin890** [Jozufozu/ExNihiloOmnia#41]
Well if optifine, tinkers' construct, and ex nihilo omnia are run in a modpack together a crash occurs with Tinker's rendering as the issue.
Mod and version list:
Optifine - version 1.10.2 HD U C3
 TConstruct - version 1.10.2 - 2.5.2
 Ex Nihilo Omnia - 1.1.1
Mantle - 1.10.2 - 1.0.0

[crash-2016-09-26_17.22.28-client.txt](https://github.com/Jozufozu/ExNihiloOmnia/files/494148/crash-2016-09-26_17.22.28-client.txt)

Reason why I sent you this is due to it only occuring after I had updated from version 1.1.0 to 1.1.1 of your mod.

**Comment by Jozufozu** [comment]
Does anything bad happen without optifine? I'm not home right now so I can't test it

**Comment by Ravin890** [comment]
Without optifine it runs fine, or if i downgrade ex nihilo omnia to version 1.1.0 (older computer so optifine usually helps the most for me)
And take your time, if anything you should write not compatible with optifine if Tinkers' Construct is in the modpack.

**Comment by Jozufozu** [comment]
I'll see what I can do, but optifine is known for messing up rendering stuff

**Comment by ghost** [comment]
I had this same issue.

Also, while using Optifine (I don't know what option causes it though), all blocks have the default missing texture icon.

**Comment by ghost** [comment]
I guess I'll just use 1.1.0 for now.

**Comment by DatrixTHLK** [comment]
Tinker's Construct and Optifine tend not to play nice together. This has always been the case ever since Minecraft 1.7.2 or earlier.

**Comment by Jozufozu** [comment]
Optifine is dumb, I love it though. Now Ex Nihilo, Optifine, and Tinkers' Construct can all be friends.

**Comment by Ravin890** [comment]
lol. Well thats good.

**Comment by DatrixTHLK** [comment]
I like how stable it makes my game. I don't consider it dumb though. What rendering issues does it have? I'm unaware of them.

**Comment by Jozufozu** [comment]
Optifine itself doesn't have any rendering issues, and I believe it actually improves rendering. However, in order to improve rendering it has to change the rendering code, which many mods make liberal use of. Because of this, any mod that is heavy on fancy animated blocks is likely to have some form of graphical artifacts with them. Note that this is based off my understanding of optifine, which is not at all in depth.

**Comment by DatrixTHLK** [comment]
I see. That information is very handy. Thanks.
