### ISSUE TITLE
Support for TOP (The One Probe)

### ISSUE THREAD

**Issue by MatthiasMann** [Jozufozu/ExNihiloOmnia#48]
I would be nice to have support for TOP in addition to WAILA:
http://modwiki.temporal-reality.com/mw/index.php/API_TOP-1.9
https://github.com/McJty/TheOneProbe/tree/1.10/src/main/java/mcjty/theoneprobe/api

**Comment by Jozufozu** [comment]
Added in fafc970bfd04ef428314992037d0b4cb9189f488
