### ISSUE TITLE
Broken Script? + Barrel Bug-Unlimited composting-.

### ISSUE THREAD

**Issue by wentehcoolest** [Jozufozu/ExNihiloOmnia#58]
Hammering gravel drops only itself not sand. I'm using v1.1.4

edit: I found some other cool stuffs happening. 

![barrel bug](https://cloud.githubusercontent.com/assets/21966744/19334611/af3c7744-912f-11e6-9a06-726e41c54d52.jpg)
![barrel bug 1](https://cloud.githubusercontent.com/assets/21966744/19334613/ba5120b2-912f-11e6-8021-4cd0a421fe0f.jpg)
![barrel bug 2](https://cloud.githubusercontent.com/assets/21966744/19334617/c23b429e-912f-11e6-8126-7076ec5d3c87.jpg)

Any single item compost material + empty barrel(wood)  have not tested on other types.

**Comment by Jozufozu** [comment]
That is odd, it works fine for me

**Comment by Drakma** [comment]
What hammer are you using?

**Comment by Jozufozu** [comment]
I was using diamond

**Comment by wentehcoolest** [comment]
so Wood stone and iron does not work, as intended?

**Comment by wentehcoolest** [comment]
the barrel issue just got fixed by adding ex compressum wut? But the hammer thing is not.

**Comment by Jozufozu** [comment]
Just went back and tried again, it works with all of them
