### ISSUE TITLE
Ex Nihilo Omnia server play with spongeforge

### ISSUE THREAD

**Issue by BakermanLP** [Jozufozu/ExNihiloOmnia#59]
Hello,

I have a problem with exnihiloomnia-1.1.4 and spongeforge-1.10.2-2098-5.0.0-BETA-1798. WIthout spongeforge I am getting drops from the sieve, with installed spongeforge I don't get any drops.

Forge Version is 2098.

Do you have any idea, what this could cause?

On the other side it works with ExCompressum_1.10.2-2.0.40 in the same setup.

Thanks in advance

Michael (aka BakermanLP)

**Comment by Jozufozu** [comment]
Fixed, not sure when, but it works now
