### ISSUE TITLE
Sieve not loading custom recipes

### ISSUE THREAD

**Issue by Johnne25** [Jozufozu/ExNihiloOmnia#60]
In the /Users/jer_mac/Library/Application Support/minecraft/config/ExNihiloOmnia/registries/Sieve folder I added a new Jason file called 'naval.json'.

That file contains:
{
  "recipes": [
    {
      "id": "minecraft:soul_sand”,
      "meta": 0,
      "behavior": "meta_ignored",
      "rewards": [
        {
          "id": "minecraft:ender_pearl”,
          "meta": 0,
          "amount": 1,
          "baseChance": 100
        }      ]
    }
  ]
}

The goal being I want an ender pearl when I sift soul sand.  However, it does not work. 
The overal goal is to have only a small chance to get a pearl, but for testing I have it set to 100.

**Comment by Johnne25** [comment]
I should have mentioned, I am running Minecraft 1.10.2, latest Forge and your latest release.

**Comment by Farronox** [comment]
Version 1.1.4, Forge 2095.

Works fine for me.

**Comment by GatorThing** [comment]
I am actually running into a similar problem with a code that sieves different rewards from sand and red_sand. I had posted this on the curse-forge page but haven't had any feed back. The way I want this to work is for red_sand to drop items A,B,and C while sand drops D,E, and F but the way its processing it is that sand drops all six and red sand is not sieve-able.

The code can be found here: http://pastebin.com/LCsHRtVa

Im currently running Forge 2099 and ENO 1.1.4 and have turned off the default sieve recipes

Any feed back is appreciated

**Comment by wentehcoolest** [comment]
doesn't it have to be named sieve.json to work?

**Comment by GatorThing** [comment]
No the one that ive supplied on pastebin is currently named sand.json and it still has some functioning behavior

**Comment by Johnne25** [comment]
Used the file included in PASTEBIN as a template and named it sieve.json just to be safe.  It works now.

Thanks TONS for the fast response.
