### ISSUE TITLE
Lagging in Ver. 1.1.4

### ISSUE THREAD

**Issue by CaptLeeb** [Jozufozu/ExNihiloOmnia#61]
When I use the latest version of Ex Nihilo Omnia, slowly my world becomes laggier and laggier. Testing it in a world, at first when you break a block, the drop appears immediately, then after waiting a little while, if you mine a block, the drop appears a second later after you finished mining it. After a while, it will not ever let me mine a block, it just ends up reappearing as if it was never broken to begin with.

I tested this to make sure it wasn't an interaction between it and another mod, it seems to solely be Ex Nihilo's fault. I am not sure what seems to be causing this issue. Downgrading to Ver. 1.1.3 seems to fix the problem.

**Comment by Jozufozu** [comment]
I'm trying to fix this, it has something to do with moss growth, so if you disable that in the config it should fix it for now.

**Comment by CaptLeeb** [comment]
Cool, thank you for the response! I didn't want to have to take this mod out of my Skyblock map.

**Comment by jdratlif** [comment]
I see allow moss spreading in the barrel options and can moss spread at all in world manipulation. Do you need to disable both of these options?

**Comment by sscards55** [comment]
If I'm not mistaken you're calling the spread moss code every tick which causes a lot of excess garbage for the GC to have to take care of. I recommend you add a random chance variable for spreading the moss [here](https://github.com/Jozufozu/ExNihiloOmnia/blob/master/src/main/java/exnihiloomnia/world/manipulation/Moss.java#L38).
![enomgc](https://cloud.githubusercontent.com/assets/5591207/19826511/6d7f4caa-9d41-11e6-9f87-cd9bafb13c88.png)
