### ISSUE TITLE
Enderio fluid pipes don't connect to the crucible

### ISSUE THREAD

**Issue by Renadarain** [Jozufozu/ExNihiloOmnia#7]
Hi :)

Last night trying to connect the fluid conduits to the crucible resulted in a crash to desktop.  I've tried again today and the item conduits connect just fine but the fluid ones don't.

Regards,
Renada

**Comment by Renadarain** [comment]
Hi :)

Do you know if there will be a fix for this? After todays update the fluid pipes still don't connect to the crucible to drain lava out although the client doesn't crash anymore.

Regards,
Renada

**Comment by Jozufozu** [comment]
I really don't know what's wrong, it probably has something to do with how IFluidhandler was implemented, I'm still looking at it, as well as IInventory for the crucibles.

**Comment by BlayTheNinth** [comment]
You need to support capabilities (IItemHandler and IFluidHandler), it's the cool new thing that replaces IInventory and the old IFluidHandler. Same for #1.

See https://github.com/blay09/ExCompressum/blob/1.10.2/src/main/java/net/blay09/mods/excompressum/tile/TileWoodenCrucible.java#L186-L203 for reference.

**Comment by Jozufozu** [comment]
Thank you!

**Comment by Renadarain** [comment]
Thank you both :)
