### ISSUE TITLE
Build instructions or jenkins

### ISSUE THREAD

**Issue by BakermanLP** [Jozufozu/ExNihiloOmnia#70]
Hello,
I wanted to test out the new commits here, but:
- I don't get this mod compiled, because of missing dependencies
- There is no jenkins available to download the latest versions
- There is no new download on Curseforge

Thanks in advance

Michael (aka BakermanLP)

**Comment by jdratlif** [comment]
I was just about to open a similar request.

I downloaded the git master, ran gradlew build, but it stops and complains about missing Tinker's code. I tried grabbing the jars from progwml's maven and putting them in the lib folder, but that didn't help. I also tried extracting the tinker's source into the src here, but it complained about Java 8 lambda constructs, and that went over my head, so I gave up on that.

:deobfCompileDeobfDepTask0 SKIPPED
:deobfCompileDeobfDepTask1 SKIPPED
:deobfCompileDeobfDepTask2 SKIPPED
:deobfCompileDeobfDepTask3 SKIPPED
:deobfCompileRemapDepSourcesTask4 SKIPPED
:deobfCompileRemapDepSourcesTask5 SKIPPED
:deobfCompileRemapDepSourcesTask6 SKIPPED
:deobfCompileRemapDepSourcesTask7 SKIPPED

I don't know much about gradle or building minecraft mods, but these lines from the build output struck me as interesting. There appear to be four defined deobfCompile tasks in the dependencies, so why were they skipped?

http://pastebin.com/v4ZkcjeK -- pastbin of my build log from a freshly unzipped git clone.

Thanks.

**Comment by Jozufozu** [comment]
Try running it with "--refresh-dependencies", see if that helps

**Comment by jdratlif** [comment]
No change. It just doesn't think it needs to get any dependencies.

**Comment by jdratlif** [comment]
The updates in commit https://github.com/Jozufozu/ExNihiloOmnia/commit/4593da85922a6f519b7a2779827a0b597eb3d3f9 fixed this. I can compile the code now.
