### ISSUE TITLE
Null pointer error with bucket.

### ISSUE THREAD

**Issue by Zarepheth** [Jozufozu/ExNihiloOmnia#75]
I was about to toss a bucket of lava on a block of obsidian, but in attempting to select the bucket, the game froze and eventually crashed to the desktop. The crash log indicates a Null Pointer error in the ExNihiloOmnia module.

> Thread: Client thread
> Stacktrace:
> 	at **exnihiloomnia.items.ENOBucketHandler.bucketFill**(ENOBucketHandler.java:49)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_398_ENOBucketHandler_bucketFill_FillBucketEvent.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	...

I've attached the crash log. I hope that helps in diagnosing the problem.

[fml-client-latest.zip](https://github.com/Jozufozu/ExNihiloOmnia/files/561056/fml-client-latest.zip)

**Comment by BakermanLP** [comment]
Seems to be similar to the above one:
http://pastebin.com/YNDXMutT
