### ISSUE TITLE
Implement Ex Nihilo Scented Artificial Hive

### ISSUE THREAD

**Issue by Farronox** [Jozufozu/ExNihiloOmnia#78]
A suggestion. I've been looking for a good way to generate hives or allow the player to somehow otherwise get more forestry bee princesses in a void world. 

Finally I googled it and found this gem. Which is exactly what I was hoping for. 
https://ftbwiki.org/Scented_Artificial_Hive

**Comment by Onigeshi** [comment]
Anything yet? This is 22 days old.. I would really love to have a way to get bees.. From what I see everything is there, we just need the artificial hive item

**Comment by Jozufozu** [comment]
I'm sorry for the wait, I've had a lot of things going on, but I should be able to get this done this weekend

**Comment by Jozufozu** [comment]
Added in f97f52074aeb702b7eb481fd426430af5e6c4b71
