### ISSUE TITLE
Request | Improve Ex Nihilo with AE2

### ISSUE THREAD

**Issue by gilyerm** [Jozufozu/ExNihiloOmnia#79]
Mod developer, please add the Costum recipes for AE2 ,for sieve and the compost ,from SkyFactory 2.5 to Ex Nihilo Omnia in 1.10.2.
or
please tell me how to add it to a modpack that i develope in 1.10.2.

**Comment by Jozufozu** [comment]
You would probably use something like [Crafttweaker](https://minecraft.curseforge.com/projects/crafttweaker) to change recipes

**Comment by Jozufozu** [comment]
That is for crafting, if you want sieve, barrel, compost or hammer recipes you would use my json system.

**Comment by Ravin890** [comment]
is it possible to do something like put something into a barrel of something else to get an item? (e.g. putting skystone dust into a barrel of lava for skystone)

**Comment by Jozufozu** [comment]
No, I might add that in a future update, however.

**Comment by Ravin890** [comment]
I think that might be what gilyern was talking about originally

**Comment by Jozufozu** [comment]
Okay, I wasn't sure

**Comment by Ravin890** [comment]
Well the sieve part you were on right track, but the compost he used the wrong word. But with skyfactory there was additional barrel input/output that were included. So that was what i thought when he said that. (I could always be overthinking what s/he originally said though)

**Comment by gilyerm** [comment]
That what i originally meant, to add the ability to putting skystone dust into a barrel of lava for skystone, and from sieve dust to get skystone dust.
But until you done it can you tell me how to do it?
And another thing please add the ability while you working on the other thing to put sapling and leaves form forestry mod (or any mod with sapling and leaves) to make dirt?

**Comment by Ravin890** [comment]
The leaves thing is composting and there is a file in the config folder telling how to add it. You just need to get the ingame item name first

**Comment by gilyerm** [comment]
So how to do it?

**Comment by Ravin890** [comment]
How to format file is told within configs. The item name may be found with crafttweaker if the tooltip command works or if another mod dumps the item names that are ingame. Not at a pc so i can't check configs.

**Comment by Ravin890** [comment]
*for name of item, you will need a mod, so something that can dump the data or maybe crafttweaker if it has the tooltip command (not at computer so i can't edit nor view any config stuff)
