### ISSUE TITLE
Latest ExNO JEI and Enderio

### ISSUE THREAD

**Issue by vibes81** [Jozufozu/ExNihiloOmnia#81]
Hi,

Whenever I try to update Ex Nihilo Omnia to version 1.1.5 for minecraft 1.10.2 JEI recipes for enderIO break and can no longer be viewed. That is JEI no longer lists any enderIO related recipes for its machines (although they still work), If I downgrade to 1.1.4 all works as expected. I`am not sure where I should report this (maybe enderIO?) but I figured Id start here as this is the mod that affects it when updating.

**Comment by Ravin890** [comment]
If you watch direwolf's forgecraft series, it seems that enderIO's recipes are kinda strange for now. Is baubles in your pack as well?

**Comment by vibes81** [comment]
Hi, yes I do have baubles installed in the pack and I will checkout the video. I did notice one version of JEI broke the enderio recipes a few versions back now I think about it oh well not to worry I can use the older version for now

**Comment by Ravin890** [comment]
Only reason i mentioned the vid is cause enderio recipes are broken in there as well but ex nihilo isn't in it

**Comment by Jozufozu** [comment]
I'm pretty sure this isn't a problem anymore, and hasn't been for a while.
