### ISSUE TITLE
Empty iron bucket the right mouse button air will collapse

### ISSUE THREAD

**Issue by Xiaoyan366** [Jozufozu/ExNihiloOmnia#83]
Empty iron bucket the right mouse button air will collapse
Right-click the air
This is an error report
[crash-2016-11-05_22.06.52-client.txt](https://github.com/Jozufozu/ExNihiloOmnia/files/573236/crash-2016-11-05_22.06.52-client.txt)

**Comment by Syndaryl** [comment]
Possibly related to #82

**Comment by Xiaoyan366** [comment]
Error code seems to be the same

![qq 20161105222855](https://cloud.githubusercontent.com/assets/1548663/20030803/46ff0edc-a3a7-11e6-81f1-37371f35f640.png)

**Comment by Xiaoyan366** [comment]
Are you also empty bucket crash? @Syndaryl 

I think you only install exnihiloomnia-1.1.5 Using an empty bucket will also crash

**Comment by Syndaryl** [comment]
@Xiaoyan366 Yes, right click empty bucket crash. It does not crash with every right click using an empty bucket, but it crashes often.

It does not crash when I use a full bucket to fill something, or to put water on the ground.
