### ISSUE TITLE
End cake Broken?

### ISSUE THREAD

**Issue by Farronox** [Jozufozu/ExNihiloOmnia#85]
Placeable, but seems to have broken texture and unable to eat/teleport 

![2016-11-06_21 38 37](https://cloud.githubusercontent.com/assets/22330373/20045759/a3403a3c-a469-11e6-9b2c-e2ebb17a9216.png)

**Comment by Jozufozu** [comment]
You have to be hungry to eat it, but you can disable that in the config.
As for the waila thing, who knows. TOP works just fine.

**Comment by Farronox** [comment]
Looks like the Void End=True option crashes the game. 

http://pastebin.com/Kvejg0fv
