### ISSUE TITLE
[ISSUE] Veinminer Compatibility

### ISSUE THREAD

**Issue by NightOps007** [Jozufozu/ExNihiloOmnia#87]
With veinminer installed along with this (exnihiloomnia-1.1.6 & VeinMiner-0.34.1-1.9r571+73be663), it takes quite some time to load; appears to freeze while loading at:
   Loading - Initializing mods Phase 3
   InterModComms$IMC - Vein Miner
I first found this in a pack with 100+ mods, but was able to reproduce it with just these two while troubleshooting the problem.
Found that the options in ExNihiloOmnia.cfg were responsible. Specifically the B:"VeinMiner: register tools"=true config. While it is not actually frozen and continues after a minute or two, it caused me to believe that it was frozen. The added load time and the perception of a frozen game is problematic. Can this be fixed? I found that a good workaround for me is to set the option to false after the first run. Veinminer has been configured that way and keeps those settings.

**Comment by Jozufozu** [comment]
Thank you! I think I know what's causing this and I'll start work on a fix as soon as possible.

**Comment by Jozufozu** [comment]
It's all good now, fixed in 1.1.7

**Comment by NightOps007** [comment]
Thanks for the quick turn around on this issue.
