### ISSUE TITLE
Unable to extract items from sieve

### ISSUE THREAD

**Issue by LegendLength** [Jozufozu/ExNihiloOmnia#89]
In 1.1.6 I'm not able to extract items from a sieve using hoppers or Extra Utilities item nodes.

The config does have pipe interaction enabled:

   B:"sieve hopper/pipe interaction"=true

The sieve was being automated by a "mechanical user" block from extra utils but I imagine that won't affect the result.

**Comment by Jozufozu** [comment]
There are no items to extract. The sieve should still drop the sifting drops into the world

**Comment by Jozufozu** [comment]
The 
B:"sieve hopper/pipe interaction"=true
Is only for inserting items

**Comment by LegendLength** [comment]
Ok thanks.

But I believe it's still not possible to automate sieves which makes late game difficult.  I know this follows the same design as the original sieve in Ex Nihilo although people normally added Ex Astris with the auto sieve in 1.7.10 .

Would you consider allowing some sort of late game with sieves by giving it an output?
