### ISSUE TITLE
[1.1.7] Server crash upon client connection: NoSuchFieldError: colors

### ISSUE THREAD

**Issue by RealGrep** [Jozufozu/ExNihiloOmnia#90]
I can't log in without the server crashing with the latest version (1.1.7). I get a NoSuchFieldError: colors from exnihiloomnia.blocks.leaves.TileEntityInfestedLeaves.<init>.

Here's the crash log: http://hastebin.com/yayuvuhalu.scala

This is with Ex Nihilo Omnia version 1.1.7 on MC 1.10.2, with Forge version 2125.

**Comment by RealGrep** [comment]
Ok, little bit of poking around in the source, and it's because there's still a reference to the field 'colors' in the init on the server side. So it bombs on the server. One solution is to just remove the SideOnly annotation on the field.
EDIT: I did so and rebuilt it, and that does indeed fix the issue. Might be a more elegant way to fix it, though.

**Comment by Jozufozu** [comment]
Thank you! That's on me for not debugging the server :/ I'll be able to have a fix out later today, once i get home.
