### ISSUE TITLE
[1.1.8] Netherrack on fire under crucible only works very briefly

### ISSUE THREAD

**Issue by RealGrep** [Jozufozu/ExNihiloOmnia#91]
Since at least 1.1.7, lit netherrack under a crucible doesn't work properly. It will work for a few seconds, and then stop working. The One Probe reports a speed, then rapidly says: "No Heat Source". Lava seems to work properly.

Also, though a torch placed on top of a block under the crucible works, placing the torch on the side of an adjacent block (below the y level of the crucible, of course) such that the torch is still under the crucible doesn't work anymore. I assume you were doing stuff in that bit of code. Seems to be issues.

Thanks!

**Comment by gkuba** [comment]
This is still an issue in the latest 1.1.8 version
