### ISSUE TITLE
Crucible doesn't cook Cobblestone

### ISSUE THREAD

**Issue by DatrixTHLK** [Jozufozu/ExNihiloOmnia#94]
Hello,

The older version 1.1.6 seems to have this issue nullified. When I start cooking cobblestone it just sits there and it doesn't even melt or turn into lava. Just thought you'd like to be made aware of this, if you aren't already.

Picture of issue:
![Cobblestone just sitting there](http://tinypic.com/r/2nu0fok/9)

Minecraft 1.10.2
Forge:12.18.2.2151
Ex Nihilo Omnia: 1.1.8

Here is the FML Log of the Issue just incase: https://gist.github.com/DatrixTHLK/41744871b95cc5d4b16bad765121ddae

**Comment by Jozufozu** [comment]
This is fixed already, it was reported in #91. For now you can use an other heat source, as it is only an issue with fire. I should be able to have an update out tomorrow.

**Comment by DatrixTHLK** [comment]
I was a bit slow in putting this issue up it would seem. Thanks for the fix and the response.
