### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid (WAWLA interraction)

### ISSUE THREAD

**Issue by jena-s-lab** [Jozufozu/ExNihiloOmnia#96]
Hello, thank you for your awesome mod.

Scenario:
Crash when hovering the witchwater bucket in the creative inventory.

[Logs](https://gist.github.com/kane-thornwyrd/cad4fc5309ab62ee7a7f8d0a1ab421e7)

Issue mirrored as https://github.com/Darkhax-Minecraft/WAWLA/issues/60

**Comment by jena-s-lab** [comment]
Also crash on Forge 12.18.2.2151

**Comment by Darkhax** [comment]
I believe this issue is on ExNihiloOmnia's end. Wawla is calling `FluidUtil#getFluidContained(ItemStack stack)` on your stack. That is a utility provided by forge and should just return null if a FluidStack can not be created.

**Comment by Jozufozu** [comment]
Fixed with the new universal porcelain bucket

**Comment by jena-s-lab** [comment]
Fix confirmed in version 1.2.0 ! Thank you for your hard work !
