### ISSUE TITLE
latest ex nihilo omina-1.2.0 barrels not breaking

### ISSUE THREAD

**Issue by SDUBZ** [Jozufozu/ExNihiloOmnia#98]
also to be noted that the barrels i put saplings in doesnt give me dirt back,also the ore sand bugs out on placement and disapears only way to fix it is to restart world or pack

please reply asap

**Comment by Jozufozu** [comment]
What do you mean by "not breaking"?
Saplings should give grass when composted.
Nothing is wrong with ore sand for me, could you give me a screenshot?

**Comment by SDUBZ** [comment]
it breaks doesnt drop it self and becomes like a invisible block

**Comment by SDUBZ** [comment]
heres a clip of a streamer that is playing my pack for the barrels https://clips.twitch.tv/brahemic/WonderfulMuleSMSkull

**Comment by AntiDruid** [comment]
Hey I'm having the same problem as SDUBZ. Whenever a used barrel is broken it disappears and glitches out. Right clicking it or placing a block makes it appear again. Although, when a barrel has a finished product in it (like dirt from composting) it will drop the barrel and the item.

Here's what I recorded of it:
https://www.youtube.com/watch?v=hwLRvDAe3WQ
https://www.youtube.com/watch?v=v7Cts0xGvSE
